export const dynamic = "force-dynamic";

import type { Metadata } from "next";
import { type FxDecision } from "@/lib/optimizely/experimentation";
import { getOptimizelyUser } from "@/lib/optimizely/user";
import { getVisitorContext } from "@/lib/optimizely/visitor";

export const metadata: Metadata = {
  title: "Feature Experimentation Demo",
};

// ---------------------------------------------------------------------------
// Code snippets
// ---------------------------------------------------------------------------

const IMPRESSION_SNIPPET = `// src/app/[[...slug]]/page.tsx
// After Graph returns the page, check whether it served a CMS variation.
// If it did, call decide() with an empty options array so FX records the user
// in experiment results. The first decideAll() was routing-only (DISABLE_DECISION_EVENT).

const servedVariation = page._metadata?.variation ?? null;

if (servedVariation) {
  const exposedFlag = Object.values(decisions).find(
    (d) => d.variationKey === servedVariation
  );
  if (exposedFlag) {
    // Empty options → no DISABLE_DECISION_EVENT → impression fires to FX analytics
    // void discards the return value — we only care about the side effect here
    void user.decide(exposedFlag.flagKey, []);
  }
}`;

const DECISION_SNIPPET = `import { getOptimizelyUser } from "@/lib/optimizely/user";

export default async function MyPage() {
  const user = await getOptimizelyUser();

  // Evaluate without firing an impression (default: DISABLE_DECISION_EVENT)
  const decision = user.decide("subscribe_button");
  if (!decision.enabled) return null;

  // Once you know the variation will be shown, fire the impression:
  void user.decide("subscribe_button", []);

  // Variables come back typed — you cast to the type you expect
  const title = decision.variables.subscribe_title as string;
  return <Banner title={title} variation={decision.variationKey} />;
}`;

const VARIATIONS_SNIPPET = `// src/app/[[...slug]]/page.tsx
import { getOptimizelyUser } from "@/lib/optimizely/user";
import { getClient } from "@optimizely/cms-sdk";

async function CmsPage({ params }) {
  // Step 1 — evaluate all FX flags (userId + attributes from cookies automatically)
  const user = await getOptimizelyUser();
  const decisions = user.decideAll();

  // Step 2 — collect active variation keys (skip "off")
  const activeVariations = Object.values(decisions)
    .filter((d) => d.enabled && d.variationKey && d.variationKey !== "off")
    .map((d) => d.variationKey as string);

  // Step 3 — pass them to Graph as a variation filter
  //   includeOriginal: true → users NOT in an experiment still see original content
  const variationOption = activeVariations.length > 0
    ? {
        variation: {
          include: "SOME" as const,
          value: activeVariations,   // e.g. ["banner1", "contribute"]
          includeOriginal: true,
        },
      }
    : undefined;

  // Step 4 — Graph returns the CMS variant whose key matches, or falls back
  const client = getClient();
  const [page] = await client.getContentByPath(\`/en/\${slug}/\`, variationOption);
  return <OptimizelyComponent content={page} />;
}`;

const GRAPH_QUERY_SNIPPET = `# Theoretical GraphQL generated by getContentByPath("/en/", variationFilter)
# when the user is bucketed into the "personal" variation:

query {
  _Content(
    where: {
      _metadata: { url: { default: { eq: "/en/" } } }
    }
    variation: {
      include: SOME
      value: ["personal"]
      includeOriginal: true   # always include the base — safe fallback for non-experiment users
    }
    limit: 10
  ) {
    items {
      _metadata {
        key
        version
        variation       # "personal" | null (base version)
        url { default }
      }
      ... on HomePage {
        composition { ... }
      }
    }
  }
}

# Graph returns TWO items:
#   items[0] → base homepage          (variation: null)
#   items[1] → "personal" variation   (variation: "personal")
#
# The code picks items[1] because it matches activeVariations.
# If no matching CMS variation exists, includeOriginal: true ensures
# items[0] (the base) is returned — experiment is safe to deploy before
# editors create any CMS variations.`;

const MIDDLEWARE_SNIPPET = `// src/middleware.ts
import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";

export function middleware(req: NextRequest) {
  const res = NextResponse.next();

  // Only one cookie — a stable visitor ID for consistent bucketing.
  // Device type is read from the User-Agent header server-side (no cookie = GDPR safe).
  if (!req.cookies.get("optimizelyEndUserId")) {
    res.cookies.set("optimizelyEndUserId", crypto.randomUUID(), {
      maxAge: 60 * 60 * 24 * 365, // 1 year
      httpOnly: true,
      sameSite: "lax",
    });
  }

  return res;
}`;

const USER_LIB_SNIPPET = `// src/lib/optimizely/user.ts
import { cache } from "react";
import { OptimizelyDecideOption } from "@optimizely/optimizely-sdk";
import { getOptimizelyClient } from "./experimentation";
import { getVisitorContext } from "./visitor";

// cache() scopes to a single HTTP request's render tree.
// Each visitor's request gets its own completely isolated user context.
// 1,000 concurrent visitors → 1,000 independent contexts. Nothing is shared.
export const getOptimizelyUser = cache(async () => {
  const [client, { userId, attributes }] = await Promise.all([
    getOptimizelyClient(),
    getVisitorContext(), // reads optimizelyEndUserId + UA header (device), demo_persona, demo_logged_in
  ]);

  const ctx = client?.createUserContext(userId, attributes);
  return {
    userId,
    // Default: DISABLE_DECISION_EVENT — evaluate without recording.
    // Pass [] to fire the impression when the variation is actually rendered.
    decide(flagKey: string, options = [OptimizelyDecideOption.DISABLE_DECISION_EVENT]) {
      return ctx?.decide(flagKey, options);
    },
    decideAll() {
      return ctx?.decideAll([OptimizelyDecideOption.DISABLE_DECISION_EVENT]) ?? {};
    },
  };
});`;

// ---------------------------------------------------------------------------
// Sub-components
// ---------------------------------------------------------------------------

function FlagCard({ decision }: { decision: FxDecision }) {
  const hasVars = Object.keys(decision.variables).length > 0;
  return (
    <div className="bg-surface-lowest border border-ghost-border rounded-2xl p-5 flex flex-col gap-3">
      <div className="flex items-start justify-between gap-2">
        <code className="font-mono text-sm font-semibold text-on-surface break-all">
          {decision.flagKey}
        </code>
        <span
          className={`shrink-0 inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium ${
            decision.enabled
              ? "bg-green-100 text-green-800"
              : "bg-surface-low text-on-surface-variant"
          }`}
        >
          {decision.enabled ? "enabled" : "off"}
        </span>
      </div>
      {decision.variationKey && (
        <span className="self-start inline-flex items-center gap-1 px-2 py-0.5 rounded-md text-xs font-mono bg-brand/10 text-brand">
          variation: {decision.variationKey}
        </span>
      )}
      {hasVars && (
        <pre className="bg-surface-low rounded-xl p-3 text-xs font-mono text-on-surface-variant overflow-auto leading-relaxed">
          <code>{JSON.stringify(decision.variables, null, 2)}</code>
        </pre>
      )}
    </div>
  );
}

function SubscribeDemo({ decision }: { decision: FxDecision | undefined }) {
  if (!decision?.enabled) {
    return (
      <div className="rounded-2xl border border-dashed border-ghost-border bg-surface-lowest p-8 text-center">
        <p className="text-sm font-mono text-on-surface-variant mb-1">subscribe_button</p>
        <p className="text-on-surface-variant text-sm">
          Flag is <strong>off</strong> — enable it in the FX dashboard to see the live subscribe CTA.
        </p>
      </div>
    );
  }

  const title =
    (decision.variables.subscribe_title as string) ||
    (decision.variationKey === "contribute" ? "Contribute to the community" : "Subscribe for updates");
  const isContribute = decision.variationKey === "contribute";

  return (
    <div
      className={`rounded-2xl p-8 text-center ${
        isContribute ? "bg-gradient-brand" : "bg-surface-lowest border border-ghost-border"
      }`}
    >
      <p
        className={`text-xs font-semibold uppercase tracking-widest mb-3 ${
          isContribute ? "text-on-brand opacity-70" : "text-on-surface-variant"
        }`}
      >
        variation: {decision.variationKey}
      </p>
      <h3
        className={`font-display text-2xl font-bold mb-4 ${
          isContribute ? "text-on-brand" : "text-on-surface"
        }`}
      >
        {title}
      </h3>
      <button
        className={`px-6 py-2.5 rounded-full text-sm font-semibold transition-opacity hover:opacity-90 ${
          isContribute ? "bg-surface text-brand" : "bg-brand text-on-brand"
        }`}
      >
        {isContribute ? "Get involved" : "Subscribe"}
      </button>
    </div>
  );
}

function Step({ number, title, children }: { number: number; title: string; children: React.ReactNode }) {
  return (
    <div className="flex gap-5">
      <div className="shrink-0 w-8 h-8 rounded-full bg-brand flex items-center justify-center text-on-brand text-sm font-bold font-display">
        {number}
      </div>
      <div className="pt-1 flex-1">
        <h3 className="font-display font-semibold text-on-surface mb-1">{title}</h3>
        <div className="text-sm text-on-surface-variant leading-relaxed">{children}</div>
      </div>
    </div>
  );
}

function CodeBlock({ code, label }: { code: string; label?: string }) {
  return (
    <div className="rounded-2xl overflow-hidden border border-ghost-border">
      {label && (
        <div className="bg-surface-low border-b border-ghost-border px-4 py-2">
          <span className="text-xs font-mono text-on-surface-variant">{label}</span>
        </div>
      )}
      <pre className="bg-surface-lowest p-6 text-xs font-mono text-on-surface-variant overflow-auto leading-relaxed">
        <code>{code}</code>
      </pre>
    </div>
  );
}

function Pill({ children }: { children: React.ReactNode }) {
  return (
    <span className="inline-flex items-center px-2 py-0.5 rounded-md text-xs font-mono bg-brand/10 text-brand border border-brand/20">
      {children}
    </span>
  );
}

function Arrow() {
  return (
    <div className="flex items-center justify-center text-on-surface-variant text-lg select-none">→</div>
  );
}

// ---------------------------------------------------------------------------
// Page
// ---------------------------------------------------------------------------

const BUCKETING_ID_SNIPPET = `import { getOptimizelyUser } from "@/lib/optimizely/user";
import { getVisitorContext } from "@/lib/optimizely/visitor";

export default async function MyPage() {
  const user = await getOptimizelyUser();
  const { bucketingId } = await getVisitorContext();

  // Normal decision — bucketed by the visitor's stable userId
  const decision = user.decide("subscribe_button");

  // Account-level decision — when logged in, bucket by account ID instead.
  // All seats on the same account see the same variation.
  // userId is still used for analytics; only bucketing is overridden.
  const accountDecision = bucketingId
    ? user.decide("subscribe_button", undefined, { bucketingId })
    : null;
}`;

export default async function FeatureFlagsDemoPage() {
  const user = await getOptimizelyUser();
  const { userId, attributes, bucketingId } = await getVisitorContext();
  const device = attributes.device as string;

  const decisions = user.decideAll();
  const subscribeDecision = decisions["subscribe_button"];
  const bucketedDecision = bucketingId
    ? user.decide("subscribe_button", undefined, { bucketingId })
    : null;

  const activeVariations = Object.values(decisions)
    .filter((d) => d.enabled && d.variationKey && d.variationKey !== "off")
    .map((d) => d.variationKey as string);

  return (
    <div className="min-h-screen bg-surface">

      {/* ── Hero ── */}
      <section className="bg-gradient-brand py-20">
        <div className="max-w-7xl mx-auto px-8">
          <p className="font-body text-xs font-semibold uppercase tracking-widest mb-4 text-on-brand opacity-70">
            Developer Demo
          </p>
          <h1 className="font-display text-4xl md:text-5xl font-extrabold text-on-brand mb-4">
            Feature Experimentation
          </h1>
          <p className="text-lg text-on-brand-muted max-w-2xl leading-relaxed">
            Optimizely Feature Experimentation runs alongside SaaS CMS on the same platform.
            Flag decisions are evaluated server-side in React Server Components — no client JS,
            no layout shift. Variation keys from FX drive which CMS content variant Graph returns,
            connecting A/B experiments directly to editor-created content variations.
          </p>
          <div className="flex flex-wrap gap-3 mt-8">
            {["✓ Server-side decisions", "Feature flags · Experiments", "Audience targeting", "Variable delivery", "CMS Variations integration"].map((t) => (
              <span key={t} className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-medium bg-badge-bg text-on-brand">
                {t}
              </span>
            ))}
          </div>
        </div>
      </section>

      <div className="max-w-7xl mx-auto px-8 py-16 space-y-20">

        {/* ── Architecture overview ── */}
        <section id="how-it-works">
          <h2 className="font-display text-2xl font-bold text-on-surface mb-2">
            How It All Fits Together <a href="#how-it-works" className="ml-1 text-brand/30 hover:text-brand transition-colors font-normal text-lg">#</a>
          </h2>
          <p className="text-sm text-on-surface-variant mb-8 max-w-3xl">
            Four steps happen on every page request. The browser never touches the SDK
            or runs an experiment script — all decisions happen server-side before HTML is streamed.
          </p>

          {/* Architecture flow */}
          <div className="grid grid-cols-1 md:grid-cols-7 gap-2 items-center mb-8">
            <div className="bg-surface-lowest border border-ghost-border rounded-2xl p-5 text-center">
              <div className="text-2xl mb-2">🌐</div>
              <p className="text-xs font-mono font-semibold text-on-surface mb-1">Browser</p>
              <p className="text-xs text-on-surface-variant">Sends <code className="bg-surface-low px-1 rounded">optimizelyEndUserId</code> cookie</p>
            </div>
            <Arrow />
            <div className="bg-surface-lowest border border-brand/30 rounded-2xl p-5 text-center">
              <div className="text-2xl mb-2">⚡</div>
              <p className="text-xs font-mono font-semibold text-on-surface mb-1">FX SDK (server)</p>
              <p className="text-xs text-on-surface-variant">
                Calls <code className="bg-surface-low px-1 rounded">decide()</code> · returns <code className="bg-surface-low px-1 rounded">variationKey</code> + variables
              </p>
            </div>
            <Arrow />
            <div className="bg-surface-lowest border border-ghost-border rounded-2xl p-5 text-center">
              <div className="text-2xl mb-2">🗄️</div>
              <p className="text-xs font-mono font-semibold text-on-surface mb-1">Graph API</p>
              <p className="text-xs text-on-surface-variant">
                Filters by <code className="bg-surface-low px-1 rounded">variation.value</code> · serves matched CMS variant
              </p>
            </div>
            <Arrow />
            <div className="bg-surface-lowest border border-ghost-border rounded-2xl p-5 text-center">
              <div className="text-2xl mb-2">📊</div>
              <p className="text-xs font-mono font-semibold text-on-surface mb-1">Bucket the user</p>
              <p className="text-xs text-on-surface-variant">
                Fire <code className="bg-surface-low px-1 rounded">decide()</code> again — records user in experiment results
              </p>
            </div>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-4">
            <div className="bg-surface-lowest border border-ghost-border rounded-2xl p-6">
              <div className="w-8 h-8 rounded-lg bg-brand/10 flex items-center justify-center mb-4">
                <span className="text-brand font-bold font-mono text-sm">1</span>
              </div>
              <h3 className="font-display font-semibold text-on-surface mb-2">Middleware sets a stable ID</h3>
              <p className="text-sm text-on-surface-variant leading-relaxed">
                On first visit, Next.js middleware writes an <code className="bg-surface-low px-1 rounded font-mono text-xs">optimizelyEndUserId</code> UUID
                cookie (1 year TTL). It&apos;s the only cookie set —{" "}
                <code className="bg-surface-low px-1 rounded font-mono text-xs">device</code> is derived from the User-Agent header server-side (no cookie stored).
              </p>
            </div>
            <div className="bg-surface-lowest border border-ghost-border rounded-2xl p-6">
              <div className="w-8 h-8 rounded-lg bg-brand/10 flex items-center justify-center mb-4">
                <span className="text-brand font-bold font-mono text-sm">2</span>
              </div>
              <h3 className="font-display font-semibold text-on-surface mb-2">FX SDK evaluates flags server-side</h3>
              <p className="text-sm text-on-surface-variant leading-relaxed">
                <code className="bg-surface-low px-1 rounded font-mono text-xs">getOptimizelyUser()</code> reads the{" "}
                <code className="bg-surface-low px-1 rounded font-mono text-xs">optimizelyEndUserId</code> cookie — it has an expiration
                date, so the same visitor gets the same bucket across return visits. React{" "}
                <code className="bg-surface-low px-1 rounded font-mono text-xs">cache()</code> deduplicates within a single page load.
                The datafile is refreshed every 60 seconds.
              </p>
            </div>
            <div className="bg-surface-lowest border border-ghost-border rounded-2xl p-6">
              <div className="w-8 h-8 rounded-lg bg-brand/10 flex items-center justify-center mb-4">
                <span className="text-brand font-bold font-mono text-sm">3</span>
              </div>
              <h3 className="font-display font-semibold text-on-surface mb-2">Graph returns the right CMS variant</h3>
              <p className="text-sm text-on-surface-variant leading-relaxed">
                Active variation keys are passed to <code className="bg-surface-low px-1 rounded font-mono text-xs">getContentByPath</code> as
                a <code className="bg-surface-low px-1 rounded font-mono text-xs">{"{ include: 'SOME', value: [...keys] }"}</code> filter.
                Graph serves the CMS content variant whose key matches — or the original if none exists.
              </p>
            </div>
            <div className="bg-surface-lowest border border-ghost-border rounded-2xl p-6">
              <div className="w-8 h-8 rounded-lg bg-brand/10 flex items-center justify-center mb-4">
                <span className="text-brand font-bold font-mono text-sm">4</span>
              </div>
              <h3 className="font-display font-semibold text-on-surface mb-2">Impression recorded in FX</h3>
              <p className="text-sm text-on-surface-variant leading-relaxed">
                After Graph confirms the CMS variation was served, a second{" "}
                <code className="bg-surface-low px-1 rounded font-mono text-xs">decide(flagKey, [])</code> fires without{" "}
                <code className="bg-surface-low px-1 rounded font-mono text-xs">DISABLE_DECISION_EVENT</code>. This sends the impression
                so FX analytics can track participants, measure lift, and declare a winner.
              </p>
            </div>
          </div>
        </section>

        {/* ── Your session ── */}
        <section id="your-session">
          <h2 className="font-display text-2xl font-bold text-on-surface mb-2">Your Session <a href="#your-session" className="ml-1 text-brand/30 hover:text-brand transition-colors font-normal text-lg">#</a></h2>
          <p className="text-sm text-on-surface-variant mb-6">
            A stable <code className="bg-surface-low px-1 rounded text-xs font-mono">optimizelyEndUserId</code> cookie
            is set by Next.js middleware on first visit. Flag decisions below are bucketed to this ID —
            reload and you always land in the same variation.
          </p>

          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
            <div className="bg-surface-lowest border border-ghost-border rounded-xl px-5 py-4 flex flex-col gap-1">
              <span className="text-xs text-on-surface-variant font-mono uppercase tracking-wider">User ID</span>
              <span className="text-sm font-mono text-on-surface">{userId.slice(0, 8)}…{userId.slice(-4)}</span>
              <span className="text-xs text-on-surface-variant">stable per browser</span>
            </div>
            <div className="bg-surface-lowest border border-ghost-border rounded-xl px-5 py-4 flex flex-col gap-1">
              <span className="text-xs text-on-surface-variant font-mono uppercase tracking-wider">Device</span>
              <span className="text-sm font-mono text-on-surface">{device}</span>
              <span className="text-xs text-on-surface-variant">derived from User-Agent header (no cookie)</span>
            </div>
            <div className={`rounded-xl px-5 py-4 flex flex-col gap-1 border ${bucketingId ? "bg-emerald-50 border-emerald-200" : "bg-surface-lowest border-ghost-border"}`}>
              <span className="text-xs text-on-surface-variant font-mono uppercase tracking-wider">Bucketing ID</span>
              <span className={`text-sm font-mono ${bucketingId ? "text-emerald-700" : "text-on-surface-variant"}`}>
                {bucketingId ?? "—"}
              </span>
              <span className="text-xs text-on-surface-variant">
                {bucketingId ? "overrides bucketing (not analytics)" : "sign in via Audience Switcher to set"}
              </span>
            </div>
            <div className="bg-surface-lowest border border-ghost-border rounded-xl px-5 py-4 flex flex-col gap-1">
              <span className="text-xs text-on-surface-variant font-mono uppercase tracking-wider">Active Variations</span>
              <span className="text-sm font-mono text-on-surface">
                {activeVariations.length === 0 ? "none" : activeVariations.join(", ")}
              </span>
              <span className="text-xs text-on-surface-variant">keys passed to Graph</span>
            </div>
          </div>

          {/* Flag decisions grid */}
          <h3 className="font-display text-lg font-semibold text-on-surface mb-4">All Flag Decisions</h3>
          <p className="text-sm text-on-surface-variant mb-5">
            Evaluated via <code className="bg-surface-low px-1 rounded text-xs font-mono">userContext.decideAll()</code>.
            Changes in the FX dashboard take effect within 60 seconds (datafile cache TTL).
          </p>
          {Object.keys(decisions).length === 0 ? (
            <div className="rounded-2xl border border-dashed border-ghost-border bg-surface-lowest p-8 text-center">
              <p className="text-on-surface-variant text-sm">
                No flags found — check that{" "}
                <code className="bg-surface-low px-1 rounded font-mono text-xs">OPTIMIZELY_FX_SDK_KEY</code>{" "}
                is set in <code className="bg-surface-low px-1 rounded font-mono text-xs">.env.local</code>.
              </p>
            </div>
          ) : (
            <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
              {Object.values(decisions).map((d) => (
                <FlagCard key={d.flagKey} decision={d} />
              ))}
            </div>
          )}
        </section>

        {/* ── Live subscribe demo ── */}
        <section id="live-demo">
          <h2 className="font-display text-2xl font-bold text-on-surface mb-2">
            Live Demo: <code className="font-mono text-2xl">subscribe_button</code> <a href="#live-demo" className="ml-1 text-brand/30 hover:text-brand transition-colors font-normal text-lg">#</a>
          </h2>
          <p className="text-sm text-on-surface-variant mb-2">
            This component is driven entirely by the{" "}
            <code className="bg-surface-low px-1 rounded text-xs font-mono">subscribe_button</code> flag
            and its <code className="bg-surface-low px-1 rounded text-xs font-mono">subscribe_title</code> variable.
          </p>
          <div className="flex flex-wrap gap-2 mb-6 text-xs text-on-surface-variant">
            <span>Variations:</span>
            <Pill>off</Pill>
            <span>·</span>
            <Pill>on</Pill>
            <span>(default title from variable)</span>
            <span>·</span>
            <Pill>contribute</Pill>
            <span>(alternate messaging + brand gradient)</span>
          </div>
          <SubscribeDemo decision={subscribeDecision} />
        </section>

        {/* ── Bucketing ID ── */}
        <section id="bucketing-id">
          <h2 className="font-display text-2xl font-bold text-on-surface mb-2">
            Bucketing ID Override <a href="#bucketing-id" className="ml-1 text-brand/30 hover:text-brand transition-colors font-normal text-lg">#</a>
          </h2>
          <p className="text-sm text-on-surface-variant mb-6 max-w-3xl">
            By default the FX SDK buckets users by their <code className="bg-surface-low px-1 rounded font-mono text-xs">userId</code>.
            Setting the reserved <code className="bg-surface-low px-1 rounded font-mono text-xs">$opt_bucketing_id</code> attribute
            overrides <em>which</em> ID drives bucketing — while keeping the original <code className="bg-surface-low px-1 rounded font-mono text-xs">userId</code> for
            analytics. This means all users sharing the same bucketing ID land in the same variation,
            regardless of their individual user IDs.
          </p>

          <div className="grid md:grid-cols-3 gap-4 mb-8">
            {[
              {
                title: "B2B / account-level experiments",
                body: "Every seat on the same company account sees the same variation. Avoids the awkward situation where user A sees Variation 1 and user B on the same account sees Variation 2 in the same meeting.",
              },
              {
                title: "Family plans & shared subscriptions",
                body: "Households or linked accounts that share access should have a consistent experience — buck by the primary account ID, not by each individual member.",
              },
              {
                title: "Gradual rollouts to accounts",
                body: "Roll out a new feature to 10% of accounts (not 10% of users). Avoids fragmenting the experience inside the same company during a staged rollout.",
              },
            ].map(({ title, body }) => (
              <div key={title} className="bg-surface-lowest border border-ghost-border rounded-2xl p-6">
                <h3 className="font-display font-semibold text-on-surface mb-2">{title}</h3>
                <p className="text-sm text-on-surface-variant leading-relaxed">{body}</p>
              </div>
            ))}
          </div>

          <CodeBlock code={BUCKETING_ID_SNIPPET} label="src/components/MyPage.tsx" />

          {/* Live comparison */}
          <div className="mt-8">
            <h3 className="font-display font-semibold text-on-surface mb-1">Live comparison — <code className="font-mono font-semibold">subscribe_button</code></h3>
            <p className="text-sm text-on-surface-variant mb-5">
              {bucketingId
                ? `Signed in as ${bucketingId}. The two decisions below may land in different variations — the normal decision is bucketed by your browser's stable userId, the account decision by the login ID.`
                : "Sign in via the Audience Switcher (bottom-right) to see the account-level decision alongside your normal decision."}
            </p>
            <div className="grid md:grid-cols-2 gap-6">
              <div>
                <p className="text-xs font-mono text-on-surface-variant uppercase tracking-wider mb-3">
                  Normal — bucketed by userId
                </p>
                <SubscribeDemo decision={subscribeDecision} />
                {subscribeDecision && (
                  <p className="mt-2 text-xs font-mono text-on-surface-variant">
                    variation: <span className="text-brand">{subscribeDecision.variationKey ?? "off"}</span>
                  </p>
                )}
              </div>
              <div>
                <p className="text-xs font-mono text-on-surface-variant uppercase tracking-wider mb-3">
                  Account — bucketed by{" "}
                  <span className={bucketingId ? "text-emerald-600" : "text-on-surface-variant"}>
                    {bucketingId ? `$opt_bucketing_id: "${bucketingId}"` : "not set"}
                  </span>
                </p>
                {bucketedDecision ? (
                  <>
                    <SubscribeDemo decision={bucketedDecision} />
                    <p className="mt-2 text-xs font-mono text-on-surface-variant">
                      variation: <span className="text-emerald-600">{bucketedDecision.variationKey ?? "off"}</span>
                    </p>
                  </>
                ) : (
                  <div className="rounded-2xl border border-dashed border-ghost-border bg-surface-lowest p-8 text-center h-full flex items-center justify-center">
                    <p className="text-sm text-on-surface-variant">
                      Sign in via the Audience Switcher to activate
                    </p>
                  </div>
                )}
              </div>
            </div>
          </div>
        </section>

        {/* ── CMS Variations — the connection ── */}
        <section id="cms-variations">
          <h2 className="font-display text-2xl font-bold text-on-surface mb-2">
            CMS Variations — Connecting FX to Content <a href="#cms-variations" className="ml-1 text-brand/30 hover:text-brand transition-colors font-normal text-lg">#</a>
          </h2>
          <p className="text-sm text-on-surface-variant mb-8 max-w-3xl">
            FX variation keys and CMS content variations share a single string contract.
            When Graph receives an active variation key, it looks for a CMS content variant
            with the same name and returns it. Editors create the variant in Visual Builder;
            the SDK wires it at request time — no code change required after initial setup.
          </p>

          {/* Flow diagram */}
          <div className="bg-surface-lowest border border-ghost-border rounded-2xl p-6 mb-6">
            <p className="text-xs font-mono text-on-surface-variant uppercase tracking-wider mb-4">
              Request flow — this demo&apos;s homepage_audience experiment
            </p>
            <div className="flex flex-wrap items-start gap-3">
              <div className="text-center">
                <div className="bg-surface-low rounded-xl px-4 py-3 mb-1 min-w-[120px]">
                  <p className="text-xs font-mono font-semibold text-on-surface">FX Dashboard</p>
                  <p className="text-xs text-on-surface-variant mt-0.5">flag: <code className="font-mono">homepage_audience</code></p>
                  <p className="text-xs text-on-surface-variant">variation: <code className="font-mono text-brand">business</code></p>
                </div>
              </div>
              <div className="flex items-center pt-4 text-on-surface-variant">→</div>
              <div className="text-center">
                <div className="bg-surface-low rounded-xl px-4 py-3 mb-1 min-w-[140px]">
                  <p className="text-xs font-mono font-semibold text-on-surface">FX SDK</p>
                  <p className="text-xs text-on-surface-variant mt-0.5">user bucketed into</p>
                  <p className="text-xs text-on-surface-variant">variationKey: <code className="font-mono text-brand">business</code></p>
                </div>
              </div>
              <div className="flex items-center pt-4 text-on-surface-variant">→</div>
              <div className="text-center">
                <div className="bg-surface-low rounded-xl px-4 py-3 mb-1 min-w-[180px]">
                  <p className="text-xs font-mono font-semibold text-on-surface">Graph query</p>
                  <p className="text-xs text-on-surface-variant mt-0.5 font-mono">variation: {"{"}</p>
                  <p className="text-xs text-on-surface-variant font-mono pl-2">include: &apos;SOME&apos;,</p>
                  <p className="text-xs text-on-surface-variant font-mono pl-2">value: [<span className="text-brand">&apos;business&apos;</span>]</p>
                  <p className="text-xs text-on-surface-variant font-mono">{"}"}</p>
                </div>
              </div>
              <div className="flex items-center pt-4 text-on-surface-variant">→</div>
              <div className="text-center">
                <div className="bg-brand/10 border border-brand/30 rounded-xl px-4 py-3 mb-1 min-w-[160px]">
                  <p className="text-xs font-mono font-semibold text-on-surface">CMS serves</p>
                  <p className="text-xs text-on-surface-variant mt-0.5">content variant</p>
                  <p className="text-xs font-mono text-brand">named &quot;business&quot;</p>
                  <p className="text-xs text-on-surface-variant text-[10px] mt-1">(or original if no match)</p>
                </div>
              </div>
            </div>
          </div>

          <div className="bg-amber-50 border border-amber-200 rounded-2xl p-5 mb-6">
            <p className="text-sm text-amber-900 leading-relaxed">
              <strong>CMS variations must be created in Visual Builder — the Management API cannot create them.</strong>{" "}
              The <code className="bg-amber-100 px-1 rounded font-mono text-xs">variation</code> field
              exists in Graph&apos;s schema but is silently ignored by the Management API on write.
              However, once created in Visual Builder each variation becomes a new draft{" "}
              <strong>version</strong> — you can discover the version number via{" "}
              <code className="bg-amber-100 px-1 rounded font-mono text-xs">GET /content/{"{key}"}/versions</code>{" "}
              and PATCH it with the correct composition + <code className="bg-amber-100 px-1 rounded font-mono text-xs">status: &quot;published&quot;</code>.
              See <code className="bg-amber-100 px-1 rounded font-mono text-xs">scripts/update-homepage-variations.ts</code>.
            </p>
          </div>

          {/* Current session's variation keys → Graph */}
          <div className="bg-surface-lowest border border-ghost-border rounded-2xl p-6 mb-6">
            <h3 className="font-display font-semibold text-on-surface mb-1">
              Your Variation Keys → Graph Filter
            </h3>
            <p className="text-xs text-on-surface-variant mb-4">
              This is what the live page route is passing to{" "}
              <code className="bg-surface-low px-1 rounded font-mono">getContentByPath</code> for your session right now.
            </p>
            <pre className="bg-surface-low rounded-xl p-4 text-xs font-mono text-on-surface-variant leading-relaxed overflow-auto">
              <code>
                {activeVariations.length === 0
                  ? `// No active variation keys — all flags are off or returning "off"\n// Graph will return original content on all pages\nvariationOption = undefined`
                  : `variationOption = {\n  variation: {\n    include: "SOME",\n    value: ${JSON.stringify(activeVariations)},\n    includeOriginal: true,\n  },\n}`}
              </code>
            </pre>
            {activeVariations.length === 0 && (
              <p className="text-xs text-on-surface-variant mt-3">
                Enable a flag and run an experiment in the FX dashboard, then reload — your variation key will appear above and start influencing CMS content delivery.
              </p>
            )}
          </div>
        </section>

        {/* ── Setup guide ── */}
        <section id="setup-guide">
          <h2 className="font-display text-2xl font-bold text-on-surface mb-2">
            Setting Up CMS Variations — Step by Step <a href="#setup-guide" className="ml-1 text-brand/30 hover:text-brand transition-colors font-normal text-lg">#</a>
          </h2>
          <p className="text-sm text-on-surface-variant mb-8 max-w-3xl">
            Once the integration code is in place (see below), editors can set up any number of
            content experiments without touching code. The variation key string is the only contract
            between Feature Experimentation and the CMS.
          </p>

          <div className="space-y-8 max-w-2xl">
            <Step number={1} title="Create a flag and experiment in Feature Experimentation">
              Create manually in the FX dashboard or via the REST API. This demo uses flag{" "}
              <code className="bg-surface-low px-1 rounded font-mono text-xs">homepage_audience</code> with two
              audience-targeted delivery rules and a fallback:{" "}
              <code className="bg-surface-low px-1 rounded font-mono text-xs">personal</code> (33%, audience: <code className="bg-surface-low px-1 rounded font-mono text-xs">persona == "personal"</code>),{" "}
              <code className="bg-surface-low px-1 rounded font-mono text-xs">business</code> (33%, audience: <code className="bg-surface-low px-1 rounded font-mono text-xs">persona == "business"</code>), and{" "}
              <code className="bg-surface-low px-1 rounded font-mono text-xs">off</code> (34%). The{" "}
              <code className="bg-surface-low px-1 rounded font-mono text-xs">persona</code> attribute is set from the{" "}
              <code className="bg-surface-low px-1 rounded font-mono text-xs">demo_persona</code> cookie by the Audience Switcher.
            </Step>

            <Step number={2} title="Create variations in Visual Builder, then update via script">
              Open the homepage in the CMS Visual Builder. In the right-hand panel, click{" "}
              <strong>Add variation</strong>. Create two variations named exactly{" "}
              <code className="bg-surface-low px-1 rounded font-mono text-xs">personal</code> and{" "}
              <code className="bg-surface-low px-1 rounded font-mono text-xs">business</code>{" "}
              (case-sensitive — must match the FX variation keys exactly). Each becomes a new draft version in the CMS. Then run{" "}
              <code className="bg-surface-low px-1 rounded font-mono text-xs">npx tsx scripts/update-homepage-variations.ts</code>{" "}
              to PATCH those versions with the correct compositions and publish them — no manual composition
              editing in the UI needed.
            </Step>

            <Step number={3} title="Validate with the Audience Switcher">
              Use the floating pill in the bottom-right corner to preview each variation instantly —
              no waiting for FX bucketing. Select <strong>Business Customer</strong>; the homepage should
              show &ldquo;Banking built for business&rdquo; once the CMS variation exists.
            </Step>

            <Step number={4} title="Enable the flag and start the experiment">
              Turn on the flag and launch the experiment in the FX dashboard. FX handles traffic
              allocation and bucketing; Graph handles content delivery. Analytics, winner declaration,
              and rollout happen entirely in the FX dashboard — no code changes needed.
            </Step>

            <Step number={5} title="Validate with this page">
              Reload this page — your current variation key will appear in the{" "}
              <strong>Flag Decisions</strong> grid above and in the <strong>Your Variation Keys → Graph Filter</strong>{" "}
              block. If the key matches a CMS variation, that page now serves the personalised variant.
            </Step>
          </div>
        </section>

        {/* ── Audience targeting ── */}
        <section id="audience-targeting">
          <h2 className="font-display text-2xl font-bold text-on-surface mb-2">
            Audience Targeting <a href="#audience-targeting" className="ml-1 text-brand/30 hover:text-brand transition-colors font-normal text-lg">#</a>
          </h2>
          <p className="text-sm text-on-surface-variant mb-6 max-w-3xl">
            FX attributes (like <code className="bg-surface-low px-1 rounded font-mono text-xs">device</code>) are matched
            against audiences defined in the FX dashboard. Targeting happens on the server — the
            browser never knows which audience it was matched to.
          </p>

          <div className="grid md:grid-cols-2 gap-6">
            <div className="bg-surface-lowest border border-ghost-border rounded-2xl p-6">
              <h3 className="font-display font-semibold text-on-surface mb-3">Built-in Attributes</h3>
              <div className="space-y-3">
                {[
                  { key: "device", value: device, note: "read from User-Agent header server-side (no cookie — GDPR safe)" },
                  { key: "logged_in", value: String(attributes.logged_in), note: "from demo_logged_in cookie (Audience Switcher)" },
                ].map(({ key, value, note }) => (
                  <div key={key} className="flex items-start justify-between gap-4 pb-3 border-b border-ghost-border last:border-0">
                    <div>
                      <code className="text-sm font-mono text-on-surface">{key}</code>
                      <p className="text-xs text-on-surface-variant mt-0.5">{note}</p>
                    </div>
                    <code className="text-sm font-mono text-brand shrink-0">{value}</code>
                  </div>
                ))}
              </div>
            </div>

            <div className="bg-surface-lowest border border-ghost-border rounded-2xl p-6">
              <h3 className="font-display font-semibold text-on-surface mb-3">Adding Custom Attributes</h3>
              <p className="text-sm text-on-surface-variant mb-3 leading-relaxed">
                Pass any key-value pairs as the second argument to{" "}
                <code className="bg-surface-low px-1 rounded font-mono text-xs">getAllDecisions</code>.
                Then define matching audience conditions in the FX dashboard.
              </p>
              <pre className="bg-surface-low rounded-xl p-3 text-xs font-mono text-on-surface-variant leading-relaxed">
                <code>{`// Base attributes (device, logged_in, persona) are automatic.
// For extra attributes, spread after getVisitorContext():
const { userId, attributes } = await getVisitorContext();
await getDecision("my_flag", userId, {
  ...attributes,
  plan: "premium",  // from your database
  country: "GB",    // from geo header
});`}</code>
              </pre>
            </div>
          </div>
        </section>

        {/* ── Variables ── */}
        <section id="feature-variables">
          <h2 className="font-display text-2xl font-bold text-on-surface mb-2">
            Feature Variables <a href="#feature-variables" className="ml-1 text-brand/30 hover:text-brand transition-colors font-normal text-lg">#</a>
          </h2>
          <p className="text-sm text-on-surface-variant mb-6 max-w-3xl">
            Each variation in a flag can carry typed variables — strings, booleans, numbers, or JSON.
            Variables let editors control copy, configuration, and styling without code changes.
            The <code className="bg-surface-low px-1 rounded font-mono text-xs">subscribe_button</code> flag
            uses a <code className="bg-surface-low px-1 rounded font-mono text-xs">subscribe_title</code> string
            variable to drive the CTA text.
          </p>

          <div className="grid md:grid-cols-2 gap-6">
            <div className="bg-surface-lowest border border-ghost-border rounded-2xl p-6">
              <h3 className="font-display font-semibold text-on-surface mb-3">What&apos;s available now</h3>
              {Object.keys(decisions).length === 0 ? (
                <p className="text-sm text-on-surface-variant italic">No flags found.</p>
              ) : (
                <div className="space-y-4">
                  {Object.values(decisions).map((d) => {
                    const hasVars = Object.keys(d.variables).length > 0;
                    return (
                      <div key={d.flagKey} className="pb-4 border-b border-ghost-border last:border-0">
                        <div className="flex items-center gap-2 mb-2">
                          <code className="text-xs font-mono font-semibold text-on-surface">{d.flagKey}</code>
                          {d.variationKey && <Pill>{d.variationKey}</Pill>}
                        </div>
                        {hasVars ? (
                          <pre className="bg-surface-low rounded-lg p-2 text-xs font-mono text-on-surface-variant">
                            <code>{JSON.stringify(d.variables, null, 2)}</code>
                          </pre>
                        ) : (
                          <p className="text-xs text-on-surface-variant italic">no variables defined</p>
                        )}
                      </div>
                    );
                  })}
                </div>
              )}
            </div>

            <div className="bg-surface-lowest border border-ghost-border rounded-2xl p-6">
              <h3 className="font-display font-semibold text-on-surface mb-3">Reading variables in code</h3>
              <pre className="bg-surface-low rounded-xl p-3 text-xs font-mono text-on-surface-variant leading-relaxed">
                <code>{`const decision = await getDecision(
  "subscribe_button",
  userId,
  { device, logged_in: false },
);

// Variables are Record<string, unknown>
// Cast to the type you expect
const title =
  decision.variables.subscribe_title as string;

const config =
  decision.variables.hero_config as {
    headline: string;
    cta: string;
    theme: "light" | "dark";
  };`}</code>
              </pre>
            </div>
          </div>
        </section>

        {/* ── Code snippets ── */}
        <section id="integration-code">
          <h2 className="font-display text-2xl font-bold text-on-surface mb-6">
            Integration Code <a href="#integration-code" className="ml-1 text-brand/30 hover:text-brand transition-colors font-normal text-lg">#</a>
          </h2>

          <div className="space-y-6">
            <div>
              <h3 className="font-display font-semibold text-on-surface mb-1">
                1. Middleware — stable user ID + device detection
              </h3>
              <p className="text-sm text-on-surface-variant mb-3">
                Sets first-party cookies on every request. Runs at the edge before any page logic.
              </p>
              <CodeBlock code={MIDDLEWARE_SNIPPET} label="src/middleware.ts" />
            </div>

            <div>
              <h3 className="font-display font-semibold text-on-surface mb-1">
                2. FX user helper — one user context per request
              </h3>
              <p className="text-sm text-on-surface-variant mb-3">
                The <code className="bg-surface-low px-1 rounded font-mono text-xs">optimizelyEndUserId</code> cookie has an expiration
                date, so the same visitor always lands in the same bucket — across page loads and return visits. React{" "}
                <code className="bg-surface-low px-1 rounded font-mono text-xs">cache()</code> deduplicates within a single render tree:
                cookies are read once, the SDK context is created once, and concurrent visitors each get their own independent context —
                nothing shared across users. <code className="bg-surface-low px-1 rounded font-mono text-xs">decideAll()</code> evaluates
                every flag for this visitor in one call with{" "}
                <code className="bg-surface-low px-1 rounded font-mono text-xs">DISABLE_DECISION_EVENT</code> — no impressions fired yet.
              </p>
              <CodeBlock code={USER_LIB_SNIPPET} label="src/lib/optimizely/user.ts" />
            </div>

            <div>
              <h3 className="font-display font-semibold text-on-surface mb-1">
                3. CMS page route — flags → Graph variation filter
              </h3>
              <p className="text-sm text-on-surface-variant mb-3">
                The catch-all route evaluates all flags, collects active variation keys, and passes
                them to Graph. Every CMS page automatically serves the right content variant.
              </p>
              <CodeBlock code={VARIATIONS_SNIPPET} label="src/app/[[...slug]]/page.tsx" />
              <div className="mt-4">
                <p className="text-xs text-on-surface-variant mb-2 font-medium">
                  What <code className="bg-surface-low px-1 rounded font-mono">getContentByPath</code> sends to Graph under the hood:
                </p>
                <CodeBlock code={GRAPH_QUERY_SNIPPET} label="Theoretical GraphQL (personal variation active)" />
              </div>
            </div>

            <div>
              <h3 className="font-display font-semibold text-on-surface mb-1">
                4. Fire the impression when the variation is rendered
              </h3>
              <p className="text-sm text-on-surface-variant mb-3">
                <code className="bg-surface-low px-1 rounded font-mono text-xs">user.decideAll()</code> uses{" "}
                <code className="bg-surface-low px-1 rounded font-mono text-xs">DISABLE_DECISION_EVENT</code> — flags are evaluated
                without sending an impression. Once the variation is actually rendered, call{" "}
                <code className="bg-surface-low px-1 rounded font-mono text-xs">user.decide(flagKey, [])</code> with an empty options
                array to fire the impression. This is what registers the user on the experiment results page — without it,
                the results API sees zero participants even though content is being personalised.
              </p>
              <CodeBlock code={IMPRESSION_SNIPPET} label="src/app/[[...slug]]/page.tsx" />
            </div>

            <div>
              <h3 className="font-display font-semibold text-on-surface mb-1">
                5. Using a single flag decision in a component
              </h3>
              <p className="text-sm text-on-surface-variant mb-3">
                For feature-gating or variable-driven UI outside the CMS page route. The same
                impression rule applies — call <code className="bg-surface-low px-1 rounded font-mono text-xs">user.decide(flagKey, [])</code>{" "}
                when the variation is actually rendered to fire the impression.
              </p>
              <CodeBlock code={DECISION_SNIPPET} label="src/components/SubscribeBanner.tsx" />
            </div>
          </div>
        </section>

        {/* ── Key points ── */}
        <section id="key-points" className="bg-surface-lowest border border-ghost-border rounded-2xl p-8">
          <h2 className="font-display text-lg font-bold text-on-surface mb-4">
            Key Things to Know <a href="#key-points" className="ml-1 text-brand/30 hover:text-brand transition-colors font-normal text-base">#</a>
          </h2>
          <ul className="space-y-3 text-sm text-on-surface-variant leading-relaxed">
            <li className="flex gap-2">
              <span className="text-brand font-bold shrink-0">→</span>
              <span>
                <strong className="text-on-surface">The variation key is the only contract</strong> between FX and the CMS.
                The string must match exactly (case-sensitive) between the FX variation key and the CMS variation name.
              </span>
            </li>
            <li className="flex gap-2">
              <span className="text-brand font-bold shrink-0">→</span>
              <span>
                <strong className="text-on-surface">includeOriginal: true</strong> means users outside
                the experiment always get the original content. Safe to add the filter before any CMS
                variations exist.
              </span>
            </li>
            <li className="flex gap-2">
              <span className="text-brand font-bold shrink-0">→</span>
              <span>
                <strong className="text-on-surface">Datafile is cached for 60 seconds</strong> via
                Next.js fetch revalidation. Changes in the FX dashboard propagate within one minute
                with no server restart.
              </span>
            </li>
            <li className="flex gap-2">
              <span className="text-brand font-bold shrink-0">→</span>
              <span>
                <strong className="text-on-surface">React cache() is scoped to a single HTTP request.</strong>{" "}
                Any number of server components can call <code className="bg-surface-low px-1 rounded font-mono text-xs">getOptimizelyUser()</code> —
                they all share one user context for that request. Concurrent visitors each get their own
                completely isolated context; nothing is shared across users.
              </span>
            </li>
            <li className="flex gap-2">
              <span className="text-brand font-bold shrink-0">→</span>
              <span>
                <strong className="text-on-surface">DISABLE_DECISION_EVENT</strong> suppresses
                impression events during the routing pass. Call{" "}
                <code className="bg-surface-low px-1 rounded font-mono text-xs">user.decide(flagKey, [])</code>{" "}
                only when the variation is actually rendered — the empty options array omits{" "}
                <code className="bg-surface-low px-1 rounded font-mono text-xs">DISABLE_DECISION_EVENT</code>,
                firing the impression and recording the user in FX experiment results.
              </span>
            </li>
            <li className="flex gap-2">
              <span className="text-brand font-bold shrink-0">→</span>
              <span>
                <strong className="text-on-surface">Variations work on any content type</strong> — pages,
                shared blocks, navigation. Wherever Graph accepts a variation filter, the SDK wires in
                seamlessly.
              </span>
            </li>
            <li className="flex gap-2">
              <span className="text-brand font-bold shrink-0">→</span>
              <span>
                <strong className="text-on-surface">CMS variations must be created in Visual Builder, but can then be updated via the Management API.</strong>{" "}
                The REST API silently ignores the <code className="bg-surface-low px-1 rounded font-mono text-xs">variation</code> field
                on <code className="bg-surface-low px-1 rounded font-mono text-xs">POST</code> — you cannot create a named variation programmatically.
                But creating one in the UI generates a new draft <strong>version</strong>; you can then
                <code className="bg-surface-low px-1 rounded font-mono text-xs mx-1">PATCH /content/{"{key}"}/versions/{"{version}"}</code>
                to set its composition and publish it programmatically.
              </span>
            </li>
          </ul>
        </section>

      </div>
    </div>
  );
}
